services:
  mongodb:
    image: docker.io/library/mongo:7.0
    container_name: test_mongodb_rootless
    userns_mode: keep-id
    ports:
      - "37017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/mongodb:/data/db:Z
    restart: unless-stopped
